### ISSUE TITLE
Custom stepper value broken

### ISSUE THREAD

**Issue by Victoria-3** [Eonic/EonicWeb5#14]

**Comment by trevski** [comment]
Vic, Can you provide a bit more detail on this one for me please

**Comment by Victoria-3** [comment]
When you select the number of articles per page for a module, eg news, there is an option to set a custom number of articles to be displayed, but this does not work correctly. So if you are using a 3 col grid and want to show 9 or 12 articles so the columns are even, there is no way to do this.
