### ISSUE TITLE
sequencing issue when adding to image gallery

### ISSUE THREAD

**Issue by Victoria-3** [Eonic/EonicWeb5#31]
When an image gallery list is set to page position, the images default to a strange order. The second image added is after the first, but from the third onward, the new images go at the start. So if adding six images, they would be displayed in the following order - 6th, 5th, 4th, 3rd, 1st, 2nd. I think this applies to other modules as well. Would be easier if page position defaulted to putting the newest added content at the end, ideally with a setting to switch to newest first.

**Comment by trevski** [comment]
OK I have resolved this it turns out that items related to a module were not able to be re-ordered at all.
